<?php if(isset($this->freebies)):?>
    <span class="toastercart-item-<?php echo $this->priceOption; ?>" data-sid<?php echo $this->priceOption; ?>="<?php echo $this->sid; ?>"><?php echo $this->translate('free'); ?></span>
<?php else:?>
    <?php if(!empty($this->discountList)):?>
        <div class="toastercart-item-<?php echo $this->priceOption; ?>" data-sid<?php echo $this->priceOption; ?>="<?php echo $this->sid; ?>"><?php echo $this->currency($this->price); ?>
        <?php foreach($this->discountList as $discountData):?>
            <?php if($discountData['type'] === 'percent'):?>
                <?php $discount = number_format($discountData['discount'], 2).'%'; ?>
            <?php else:?>
                <?php $discount = $this->currency($discountData['discount']); ?>
            <?php endif;?>
                <span class="item-discount <?php echo $discountData['name'];?>"><?php echo $discountData['name'].' '.$discount;?></span>
        <?php endforeach;?>
        </div>
    <?php else:?>
        <span class="toastercart-item-<?php echo $this->priceOption; ?>" data-sid<?php echo $this->priceOption; ?>="<?php echo $this->sid; ?>"><?php echo $this->currency($this->price); ?></span>
    <?php endif;?>
<?php endif;?>