<?php if(isset($this->cartItem['options'])): ?>
    <?php foreach($this->cartItem['options'] as $name => $optData): ?>
	    <div class="options">
		    <span><?php echo $name; ?>:&nbsp;</span><span><?php echo $optData['title']; ?></span>
		    <?php if(intval($optData['priceValue'])): ?>
			    <?php $price = $optData['priceValue'] + $optData['priceValue']*$this->taxRate; ?>
		        <span>(<?php echo $optData['priceSign'], ' ', (($optData['priceType'] == 'unit') ? $this->currency($price ) : $optData['priceValue'] . '%'); ?>)</span>
			<?php endif; ?>
		    <?php if(intval($optData['weightValue'])): ?>
                <span>(<?php echo $optData['weightSign'], ' ', $optData['weightValue'],' ', $this->weightSign; ?>)</span>
            <?php endif; ?>
	    </div>
	<?php endforeach; ?>
<?php endif; ?>