<?php
$this->jQuery()->addJavascriptFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/addresschain.jquery.js');
?>

<div id="checkout-widget">
	<?php echo $this->content; ?>
</div>

<script id="ShippersFormTmpl" type="text/template">
	<form id="shipper-select" method="post" enctype="application/x-www-form-urlencoded" action="<%= $('#website_url').val() %>plugin/cart/run/checkout/">
	    <h3 class="shipping-address-header"><%= caption %></h3>
	    <input type="hidden" name="check" value="shipper">
	    <% _.each(shippers, function(shipper) { %>
	        <ul id="<%= shipper.name %>-methods" class="shipping-methods" data-name="<%= shipper.name %>">
	            <li><label>...quering <%= shipper.name %>...</label></li>
	        </ul>
	    <% }); %>
	    <input type="submit" value="Apply" >
	</form>
</script>

<script id="ShipperMethodsTmpl" type="text/template">
	<% _.each(services, function(s, index){ %>
	    <% if (s.error) { %>
	    <li><label class="shipper-error"><%= s.error %></label></li>
	    <% } else { %>
	    <li>
	    <label style="cursor: pointer">
	    <input type="radio" name="shipper" value="<%= name+'::'+index %>"/><span class="shipping-method-title"><%= s.type %></span>
	    <span class="shipping-price"><%= s.price %></span></label>
	        <% if (s.descr) { %><p><%= s.descr %></p><% } %>
	    <% } %>
	<% }) %>
</script>

<style type="text/css">
	.required::after {
		content: ' *';
		color: red;
		font-weight: bold;
	}
	.notvalid {
		color: red;
	}
	#checkout-widget ul.shipping-methods li {
		list-style: none;
		padding: 5px 10px;
		margin: 0;
	}
	#checkout-widget ul.shipping-methods li label {
		cursor: pointer;
	}
	#checkout-widget ul.shipping-methods li label input[type="radio"] {
		vertical-align: middle;
		margin: 2px 4px;
	}
</style>

<script data-main="<?php echo $this->websiteUrl;?>plugins/cart/web/js/modules/checkout/main.js" src="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/require.min.js"></script>