<div>
	<?php if ($this->shippers) :?>
    <h3 class="checkout-forms-header"><?php echo $this->translate('Select shipping method');?>
        <a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_SHIPPING_OPTIONS;?>" class="checkout-edit" title="<?php echo $this->translate('Back');?>">
            &laquo;&nbsp<?php echo $this->translate('Back');?>
        </a></h3>
    <form id="shipper-select" method="post" class="toaster-checkout" enctype="application/x-www-form-urlencoded" action="<?php echo $this->actionUrl; ?>">
	    <?php foreach($this->shippers as $shipper) :?>
	    <ul id="<?php echo $shipper['name']; ?>-methods" class="shipping-methods" data-name="<?php echo $shipper['name']; ?>">
            <li>
	            <img src="<?php echo $this->websiteUrl;?>/plugins/shopping/web/images/spinner_16.gif" alt="<?php echo $this->translate('loading');?>">
	            <label>quering <?php echo $shipper['name']; ?>...</label>
 			</li>
        </ul>
	    <?php endforeach; ?>
	    <p><input type="hidden" name="step" value="<?php echo Cart::STEP_SHIPPING_METHOD; ?>"></p>
	    <p><input type="submit" value="<?php echo $this->translate('Apply');?>" ></p>
	</form>
	<?php else : ?>
	    <h3 class="checkout-forms-header">
            {$header:checkoutShippingError:static}
        </h3>
	<p class="zip-warning"><?php echo Tools_Misc::getDefaultCheckoutErrorMessage();?></p>
	<?php endif ; ?>
</div>

<script type="text/javascript">
//<![CDATA[
$('ul.shipping-methods', '#shipper-select').each(function(){
	var self = this,
		shipperName = $(this).data('name');

	$.ajax({
        url: '<?php echo $this->websiteUrl;?>plugin/'+shipperName+'/run/calculate/',
        dataType: 'json',
        success: function(response){
            var html ='';
	        $.each(response, function(index, shipper){
		        if (shipper.error) {
		            html += '<li><label class="shipper-error">'+shipper.error+'</label></li>';
	            } else {
		            html += '<li><label style="cursor: pointer">' +
		            '<input type="radio" name="shipper" value="'+shipperName+'::'+index+'"/>' +
		            '<span class="shipping-price">'+shipper.price+'</span>' +
	                '<span class="shipping-method-title">'+shipper.type+'</span>' +
		            '</label>' + ( shipper.descr ? '<p>'+shipper.descr+'</p>' : '' ) +
		            '</li>'
	            }
	        });
	        $(self).html(html);
        },
        error: function(){
            $(self).html(shipperName+' service in currently unreachable.')
        }
    });
});
//]]>
</script>