<?php
$this->inlineScript()
    ->appendFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/addresschain.jquery.js')
    ->appendFile($this->websiteUrl . 'plugins/shopping/web/js/libs/require.min.js',
        null,
        array('data-main' => $this->websiteUrl . 'plugins/cart/web/js/modules/checkout/main.js', 'noconcat' => true)
    );
?>
<input type="hidden" name="system-language" value="<?php echo Tools_Misc::getJsTranslationLanguage();?>"/>
<div class="spinner text-center"><img src="<?php echo $this->websiteUrl;?>/system/images/spinner2.gif" alt=""></div>
<div id="checkout-widget" style="display: none;">
	<?php echo $this->content; ?>
</div>