<?php
$this->jQuery()->addJavascriptFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/addresschain.jquery.js');
?>

<div class="spinner"><img src="<?php echo $this->websiteUrl;?>/plugins/shopping/web/images/spinner.gif" alt=""></div>
<div id="checkout-widget" style="display: none;">
	<?php echo $this->content; ?>
</div>

<style type="text/css">
	#checkout-widget label.required::after {
		content: ' *';
		color: red;
		font-weight: bold;
	}
	#checkout-widget input.notvalid,
	#checkout-widget select.notvalid {
		color: red;
	}
	#checkout-widget ul.shipping-methods li {
		list-style: none;
		padding: 5px 10px;
		margin: 0;
	}
	#checkout-widget ul.shipping-methods li label {
		cursor: pointer;
	}
	#checkout-widget ul.shipping-methods li label input[type="radio"] {
		vertical-align: middle;
		margin: 2px 4px;
	}
</style>

<script data-main="<?php echo $this->websiteUrl;?>plugins/cart/web/js/modules/checkout/main.js" src="<?php echo $this->websiteUrl;?>plugins/shopping/web/js/libs/require.min.js"></script>