<?php if(!isset($this->cartCheckbox)):?>
<a class="tcart-add" href="javascript:;" data-pid="<?php echo $this->productId; ?>"><?php echo $this->translate('Add to cart'); ?></a>
<script type="text/javascript">
	$(function() {
		$(document).on('click', 'a[data-pid="' + <?php echo $this->productId; ?> + '"]', function(e) {
			e.preventDefault();
			var pid  = $(this).data('pid');
			$.post('<?php echo $this->websiteUrl;?>plugin/cart/run/cart/', {
				pid     : pid,
				options : $('div[data-productid=' + pid + '] *').serialize()
			}, function() {
				window.location.href = '<?php echo $this->websiteUrl, $this->checkOutPageUrl; ?>';
			})
		})
	});
</script>
<?php else:?>
    <input type="text" name="quantityCkecked-<?php echo $this->productId;?>" maxlength="5" value="1"/>
    <input type="checkbox" class="checkAddToCart"  data-sid="" name="checkAddToCart-<?php echo $this->productId;?>" value="<?php echo $this->productId; ?>"/>
    <script type="text/javascript">
	$(function() {
		$(document).on('click', 'input[name=checkAddToCart-<?php echo $this->productId;?>]', function() {
			var pid  = $(this).val();
            var sid  = $(this).attr('data-sid');
            var qty = $('input[name=quantityCkecked-<?php echo $this->productId;?>]').val();
            showSpinner();
            if($(this).is(":checked") && qty>0){
            	$.ajax({
                    type: 'post',
                    url: '<?php echo $this->websiteUrl;?>plugin/cart/run/cart/',
                    dataType : 'json',
                    data     : {
                        pid     : pid,
                        options : $('div[data-productid=' + pid + '] *').serialize(),
                        qty     :qty
                    },
                    success : function(response){
                        if(response.error == 0){
                            $('input[name=checkAddToCart-<?php echo $this->productId;?>]').attr('data-sid', response.responseText);
                            $.ajax({
                                type: 'post',
                                url: '<?php echo $this->websiteUrl;?>plugin/cart/run/summary/',
                                dataType : 'json',
                                data     : {
                                    pid: pid,
                                    type:'json'
                                },
                                success : function(response) {
                                    if(response.error == 0){
                                        if ($("#toaster-cart").length > 0){
                                            var quantityProducts = $('#toaster-cart .cart-items-count').text();
                                            var newProductQuantity = parseInt(quantityProducts) + parseInt(qty);
                                            $('#toaster-cart .cart-items-count').text(newProductQuantity);
                                            $('#toaster-cart .cart-total-tax').text('<?php echo $this->currencySymbol;?>'+response.responseText.totalTax);
                                            $('#toaster-cart .cart-total-price').text('<?php echo $this->currencySymbol;?>'+response.responseText.total);
                                        }
                                        $('input[name=quantityCkecked-<?php echo $this->productId;?>]').attr('disabled','disabled');
                                    }
                                    hideSpinner();
                                }
                            });
                        }
                    }
                });             
                    
            }else{
               $.ajax({
                    type: 'delete',
                    url: '<?php echo $this->websiteUrl;?>plugin/cart/run/cart',
                    dataType : 'json',
                    data     : {
                        sid: sid
                    },
                    success : function(response) {
                        $.ajax({
                            type: 'post',
                            url: '<?php echo $this->websiteUrl;?>plugin/cart/run/summary/',
                            dataType : 'json',
                            data     : {
                                pid: pid,
                                type:'json'
                            },
                            success : function(response) {
                                if(response.error == 0){
                                    if ($("#toaster-cart").length > 0){
                                        var quantityProducts = $('#toaster-cart .cart-items-count').text();
                                        var newProductQuantity = parseInt(quantityProducts) - parseInt(qty);
                                        $('#toaster-cart .cart-items-count').text(newProductQuantity);
                                        $('#toaster-cart .cart-total-tax').text('<?php echo $this->currencySymbol;?>'+response.responseText.totalTax);
                                        $('#toaster-cart .cart-total-price').text('<?php echo $this->currencySymbol;?>'+response.responseText.total);
                                        $('input[name=quantityCkecked-<?php echo $this->productId;?>]').removeAttr('disabled');
                                    }
                                 }
                                 hideSpinner();
                             }
                         });
                      }
               });
            }
		})
	});
    </script>
<?php endif;?>