<?php $editMsg = '[&nbsp;'.$this->translate('edit').'&nbsp;]'; ?>
<div id="checkout-widget-preview">
	<?php if ($this->yourInformation) :?>
    <div id="checkout-user-info">
        <h3 class="checkout-widget-title">
	        <?php echo $this->translate('Your information'); ?>
	        <a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl();?>" class="checkout-edit" title="<?php echo $this->translate('Edit address');?>"><?php echo $editMsg;?></a>
        </h3>
	    <div class="preview-content">
	        <span class="fullname"><i class="ticon-user icon24"></i> <?php echo $this->yourInformation['firstname'].' '.$this->yourInformation['lastname'] ; ?></span>
	        <span class="email"><i class="ticon-email icon24"></i> <?php echo $this->yourInformation['email']; ?></span>
	    </div>
	</div>
	<?php endif; ?>

	<?php if ($this->shippingAddress) : ?>
	<div id="checkout-address-preview">
		<h3 class="checkout-widget-title <?php if ($this->shippingAddress): ?>disabled<?php endif; ?>">
			<?php if ($this->shippingData && $this->shippingData['service'] === Shopping::SHIPPING_PICKUP ):?>
			<?php echo $this->translate('Pickup location'); ?>
			<?php else : ?>
			<?php echo $this->translate('Shipping information'); ?>
			<?php endif; ?>
			<?php if ($this->shippingAddress && in_array(Cart::STEP_SHIPPING_OPTIONS, $this->returnAllowed)) : ?>
			<a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_SHIPPING_OPTIONS;?>" class="checkout-edit" title="<?php echo $this->translate('Edit address');?>"><?php echo $editMsg;?></a>
			<?php endif; ?>
        </h3>
        <div class="preview-content">
		<?php
		if ($this->shippingAddress) {
			$fullname = trim($this->shippingAddress['firstname'] .' '. $this->shippingAddress['lastname']);
			if (!empty($fullname)){ echo $fullname.'<br />'; }
            if (!empty($this->shippingAddress['phone'])) {
                echo $this->translate('Phone:') . $this->shippingAddress['phone_country_code_value'].$this->shippingAddress['phone'].'<br />';
            }
			if ($this->shippingData && $this->shippingData['service'] === Shopping::SHIPPING_PICKUP ) {?>
                <?php if($this->defaultPickup === true):?>
                    <div class="shipping-client-pickup-info">
                       <p class="company"><?php echo $this->shoppingConfig['company'];?></p>
                       <p class="phone"><?php echo $this->translate('Phone').': '.$this->shoppingConfig['phone'];?></p>
                       <p class="street-address"><?php echo $this->shoppingConfig['address1'].' '. $this->shoppingConfig['address2'];?></p>
                       <p class="locality"><?php echo $this->shoppingConfig['city'].($this->shoppingConfig['city']&&($this->shoppingConfig['state'] || $this->shoppingConfig['zip'])?',':'');?></p>
                       <p class="region"><?php $state = Tools_Geo::getStateById($this->shoppingConfig['state']); echo $state['state']; ?></p>
                       <p class="postal-code"><?php echo $this->shoppingConfig['zip'];?></p>
                       <p><?php echo $this->shoppingConfig['country'];?></p>
                    </div>
                <?php else: ?>
                    <div class="shipping-client-pickup-info">
                        <p class="company"><?php echo $this->shippingAddress['company'];?></p>
                        <p class="phone"><?php echo $this->translate('Phone').': '.$this->shippingAddress['phone'];?></p>
                        <p class="street-address"><?php echo $this->shippingAddress['address1'].' '. $this->shippingAddress['address2'];?></p>
                        <p class="locality"><?php echo $this->shippingAddress['city'].($this->shippingAddress['city']&&($this->shippingAddress['state'] || $this->shippingAddress['zip'])?',':'');?></p>
                        <p class="region"><?php $state = Tools_Geo::getStateById($this->shippingAddress['state']); echo $state['state']; ?></p>
                        <p class="postal-code"><?php echo $this->shippingAddress['zip'];?></p>
                        <p><?php echo $this->shippingAddress['country'];?></p>
                    </div>
                <?php endif;?>
            <?php } else {
                if (!empty($this->shippingAddress['email'])) { echo $this->shippingAddress['email'] .'<br />'; }
				if (!empty($this->shippingAddress['company'])) { echo $this->shippingAddress['company'] .'<br />'; }
				$addrLine = trim($this->shippingAddress['address1'] .' '. $this->shippingAddress['address2']);
				if (!empty($addrLine)){ echo $addrLine.'<br />'; }

				$state = Tools_Geo::getStateById($this->shippingAddress['state']);
				$location = join(', ', array_filter(array($this->shippingAddress['city'], $state['name'], $this->shippingAddress['zip'], $this->shippingAddress['country'])));
				if (!empty($location)){ echo $location.'<br />'; }
			}
		}
		?>
		</div>
	</div>
	<?php endif; ?>

	<?php if ($this->shippingData) : ?>
	<div id="checkout-shipping-selected">
	    <h3 class="checkout-widget-title <?php if (empty($this->shippingData)): ?>disabled<?php endif; ?>">
		    <?php echo $this->translate('Shipping method')?>
			<?php if (!empty($this->shippingData)): ?>
			<?php if (in_array(Cart::STEP_PICKUP, $this->returnAllowed)) :?>
			<a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_PICKUP;?>" class="checkout-edit" title="<?php echo $this->translate('Edit shipping method');?>">
				<?php echo $editMsg;?>
			</a>
			<?php elseif (in_array(Cart::STEP_SHIPPING_METHOD, $this->returnAllowed)) : ?>
	        <a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_SHIPPING_METHOD;?>" class="checkout-edit" title="<?php echo $this->translate('Edit shipping method');?>">
		        <?php echo $editMsg;?>
	        </a>
			<?php endif ;?>
	    </h3>
        <div class="preview-content">
            <?php
            if ($this->shippingData['service'] === Shopping::SHIPPING_PICKUP) {
                $pickupLabel = $this->translate('Pickup');
                if ($this->defaultPickup) {
                    $pickupLabel = $this->translate('Free pickup');
                }
                echo $pickupLabel . '<br />';
            } else {
                if (empty($this->shippingData['service'])) {
                    $this->shippingData['service'] = '';
                }
                echo isset($this->shippingServiceLabel) ? $this->shippingServiceLabel . ': ' . $this->shippingData['type'] : $this->translate($this->shippingData['service']) . ': ' . $this->shippingData['type'];
            }
            ?>
		</div>
        <?php endif; ?>
	</div>
	<?php endif; ?>

</div>
