<?php $editMsg = '[&nbsp;'.$this->translate('edit').'&nbsp;]'; ?>
<div id="checkout-widget-preview">
	<?php if ($this->yourInformation) :?>
    <div id="checkout-user-info">
        <h3 class="checkout-widget-title"><?php echo $this->translate('Your information'); ?></h3>
	    <div class="preview-content">
	        <span class="fullname icon-user"> <?php echo $this->yourInformation['firstname'].' '.$this->yourInformation['lastname'] ; ?></span>
	        <span class="email icon-mail"> <?php echo $this->yourInformation['email']; ?></span>
	    </div>
	</div>
	<?php endif; ?>

	<?php if ($this->shippingAddress) : ?>
	<div id="checkout-address-preview" class="mt10px">
		<h3 class="checkout-widget-title <?php if ($this->shippingAddress): ?>disabled<?php endif; ?>">
			<?php if ($this->shippingData && $this->shippingData['service'] === Shopping::SHIPPING_PICKUP ):?>
			<?php echo $this->translate('Pickup information'); ?>
			<?php else : ?>
			<?php echo $this->translate('Shipping information'); ?>
			<?php endif; ?>
			<?php if ($this->shippingAddress && in_array(Cart::STEP_SHIPPING_OPTIONS, $this->returnAllowed)) : ?>
			<a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_SHIPPING_OPTIONS;?>" class="checkout-edit" data-step="<?php echo Cart::STEP_SHIPPING_OPTIONS;?>" title="<?php echo $this->translate('Edit address');?>"><?php echo $editMsg;?></a>
			<?php endif; ?>
        </h3>
        <div class="preview-content">
		<?php
		if ($this->shippingAddress) {
			$fullname = trim($this->shippingAddress['firstname'] .' '. $this->shippingAddress['lastname']);
			if (!empty($fullname)){ echo $fullname.'<br />'; }
			if ($this->shippingData && $this->shippingData['service'] === Shopping::SHIPPING_PICKUP ) {

			} else {
				if (!empty($this->shippingAddress['email'])) { echo $this->shippingAddress['email'] .'<br />'; }
				if (!empty($this->shippingAddress['company'])) { echo $this->shippingAddress['company'] .'<br />'; }
				$addrLine = trim($this->shippingAddress['address1'] .' '. $this->shippingAddress['address2']);
				if (!empty($addrLine)){ echo $addrLine.'<br />'; }

				$state = Tools_Geo::getStateById($this->shippingAddress['state']);
				$location = join(', ', array_filter(array($this->shippingAddress['city'], $state['name'], $this->shippingAddress['zip'], $this->shippingAddress['country'])));
				if (!empty($location)){ echo $location.'<br />'; }
			}
			if (!empty($this->shippingAddress['phone'])) {
				echo $this->translate('Phone:') . $this->shippingAddress['phone'].'<br />';
			}
		}
		?>
		</div>
	</div>
	<?php endif; ?>

	<?php if ($this->shippingData) : ?>
	<div id="checkout-shipping-selected" class="mt10px">
	    <h3 class="checkout-widget-title <?php if (empty($this->shippingData)): ?>disabled<?php endif; ?>">
		    <?php echo $this->translate('Shipping method')?>
			<?php if (!empty($this->shippingData)): ?>
			<?php if (in_array(Cart::STEP_PICKUP, $this->returnAllowed)) :?>
			<a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_PICKUP;?>" class="checkout-edit" data-step="<?php echo Cart::STEP_PICKUP;?>" title="<?php echo $this->translate('Edit shipping method');?>">
				<?php echo $editMsg;?>
			</a>
			<?php elseif (in_array(Cart::STEP_SHIPPING_METHOD, $this->returnAllowed)) : ?>
	        <a href="<?php echo $this->websiteUrl . $this->checkoutPage->getUrl().'?step='.Cart::STEP_SHIPPING_METHOD;?>" class="checkout-edit" data-step="<?php echo Cart::STEP_SHIPPING_METHOD;?>" title="<?php echo $this->translate('Edit shipping method');?>">
		        <?php echo $editMsg;?>
	        </a>
			<?php endif ;?>
	    </h3>
        <div class="preview-content">
			<?php
			if ($this->shippingData['service'] === Shopping::SHIPPING_PICKUP) {
					echo $this->translate('Free pickup').'<br />';
				} else {
					echo $this->shippingData['service'] .': '. $this->shippingData['type'];
				}
			?>
		</div>
        <?php endif; ?>
	</div>
	<?php endif; ?>

</div>
