<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'plugins/cart/web/css/cart.css'); ?>
<div id="toaster-cart-holder">
	<table id="toaster-cart" class="toaster-cart-content">
		<tr>
			<th><?php echo $this->translate('Photo'); ?></th>
			<th><?php echo $this->translate('Item ID'); ?></th>
			<th><?php echo $this->translate('Description'); ?></th>
			<th><?php echo $this->translate('Quantity'); ?></th>
			<th><?php echo $this->translate('Unit price'); ?></th>
	        <?php if($this->showTaxCol): ?>
				<th><?php echo $this->translate('Tax'); ?></th>
			<?php endif; ?>
			<th><?php echo $this->translate('Price'); ?></th>
			<th><?php echo $this->translate('Remove'); ?></th>
		</tr>
		    <?php if(!isset($this->cartContent) || empty($this->cartContent)): ?>
				<tr>
					<td colspan="<?php echo ($this->showTaxCol) ? '8' : '7'; ?>" align="center">
						<?php echo $this->translate('Your cart is empty'); ?>
					</td>
				</tr>
			<?php else: ?>
				<?php foreach($this->cartContent as $sid => $cartItem): ?>
					<tr>
						<td><img src="/media/<?php echo str_replace('/', '/product/', $cartItem['photo']);?>" alt="<?php echo $cartItem['name']; ?>"></td>
						<td>
							<?php echo $cartItem['name']; ?>
							<?php if(isset($cartItem['options'])): ?>
							    <?php foreach($cartItem['options'] as $name => $optData): ?>
								    <div class="options">
									    <span><?php echo $name; ?>:&nbsp;</span><span><?php echo $optData['title']; ?></span>
									    <?php if(intval($optData['priceValue'])): ?>
									        <span>(<?php echo $optData['priceSign'], (($optData['priceType'] == 'unit') ? $this->currencySymbol : '%'), ' ', $optData['priceValue']; ?>)</span>
										<?php endif; ?>
									    <?php if(intval($optData['weightValue'])): ?>
		                                    <span>(<?php echo $optData['weightSign'], ' ', $optData['weightValue'],' ', $this->weightSign; ?>)</span>
		                                <?php endif; ?>
								    </div>
								<?php endforeach; ?>
							<?php endif; ?>
						</td>
						<td><?php echo Tools_Text_Tools::cutText($cartItem['description'], 100); ?></td>
						<td><input type="number" class="product-qty" min="0" data-sid="<?php echo $sid; ?>" data-pid="<?php echo $cartItem['id']; ?>" value="<?php echo $cartItem['qty']; ?>" /></td>
						<td><?php echo $this->currency($cartItem['price']); ?></td>
						<?php if($this->showTaxCol): ?>
							<td><?php echo $cartItem['tax']; ?></td>
						<?php endif; ?>
						<td><?php echo $this->currency($cartItem['price'] * $cartItem['qty']); ?></td>
						<td align="center">
							<a href="javascript:;" class="remove-item error ticon-close icon16" data-sid="<?php echo $sid; ?>" title="<?php echo $this->translate('remove ') ?> <?php echo $cartItem['name']; ?> <?php echo $this->translate(' from the cart') ?>"><?php echo $this->translate('Remove'); ?></a>
						</td>
					</tr>
			    <?php endforeach; ?>
			<?php endif; ?>
		</tr>
	</table>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'plugins/cart/web/js/cart.js'); ?>