<?php if($this->shippingForm !== null): ?>
    <div id="shipping-form-block">
		<span><?php echo $this->translate('ENTER YOUR SHIPPING ADDRESS'); ?></span>
	    <?php echo $this->shippingForm; ?>
    </div>
<!--	<button id="btn-checkout">--><?php //echo $this->translate('Calculate shiping and checkout'); ?><!--</button>-->
<?php endif; ?>
<div id="payment-zone" style="display: <?php echo (($this->shippingForm) ? 'none' : 'block'); ?>; width: 98%; background: #cccccc; text-align: center; height: 200px;margin: 5px 0px;">
	PAYMENTS WILL BE HERE
</div>