<?php $this->jQuery()->addJavascriptFile($this->websiteUrl.'plugins/shopping/web/js/libs/jquery/addresschain.jquery.js');?>
<script>
<?php $this->jQuery()->onLoadCaptureStart();?>
	$.fn.addressChain.options.url = '<?php echo $this->websiteUrl;?>/plugin/shopping/run/getdata/type/states/';
	$('form.toaster-checkout').addressChain();
<?php $this->jQuery()->onLoadCaptureEnd();?>
</script>

<div id="checkout-form">
<?php if ($this->form !== null) : ?>
	<span><?php echo $this->translate($this->form->getLegend()); ?></span>
    <?php echo $this->form; ?>
<?php endif; ?>
</div>

<div id="post-checkout-form" style="display: none;">
	<span><?php echo $this->translate('Your shipping address');?></span>
	<input id="edit-cart-btn" type="button" class="blue-btn" value="<?php echo $this->translate('Edit Address or quantities');?>"/>
	<p class=""></p>
</div>