<div id="cart-summary">
	<div class="cart-summary-row cart-subtotal">
		<span><?php echo $this->translate('Subtotal'); ?>:</span>
		<span id="subtotal-val">
        <?php if ($this->taxIncPrice) : ?>
            <?php echo $this->currency($this->summary['subTotal']+$this->summary['totalTax']); ?>
        <?php else : ?>
            <?php echo $this->currency($this->summary['subTotal']); ?>
        <?php endif; ?>  
        </span>
	</div>
	<div class="cart-summary-row cart-total-tax">
		<?php if ($this->taxIncPrice) : ?>
		<span><?php echo $this->translate('Inc. Tax'); ?>:</span>
		<?php else : ?>
		<span><?php echo $this->translate('Total Tax'); ?>:</span>
		<?php endif; ?>
		<span id="totaltax-val"><?php echo $this->currency($this->summary['totalTax']);?></span>
	</div>
	<div class="cart-summary-row cart-shipping">
		<span><?php echo $this->translate('Shipping'); ?>:</span>
		<span id="shipping-val"><?php echo $this->currency($this->summary['shipping']); ?></span>
	</div>
	<div class="cart-summary-row cart-total">
		<span><?php echo $this->translate('Total'); ?>:</span>
		<span id="total-val"><?php echo $this->currency($this->summary['total']); ?></span>
	</div>
</div>