<div id="cart-summary">
	<div class="cart-summary-row">
		<span><?php echo $this->translate('Subtotal'); ?></span>
		<span id="subtotal-val"><?php echo $this->currency($this->summary['subTotal']); ?></span>
	</div>
	<div class="cart-summary-row">
		<span><?php echo $this->translate('Total Tax'); ?></span>
		<span id="totaltax-val"><?php echo $this->currency($this->summary['totalTax']);?></span>
	</div>
	<div class="cart-summary-row">
		<span><?php echo $this->translate('Shipping'); ?></span>
		<span id="sipping-val"><?php echo $this->currency($this->summary['shipping']); ?></span>
	</div>
	<div class="cart-summary-row">
		<span><?php echo $this->translate('Total'); ?></span>
		<span id="total-val"><?php echo $this->currency($this->summary['total']); ?></span>
	</div>
</div>